package main

import (
	"fmt"
	"strings"
)

// Reading a report
// ================
//
// The real one this repository produced, while writing lesson 06, in a function
// whose entire job was to demonstrate correct atomic use. Kept verbatim because
// a real report is more instructive than an invented one.

// sampleReport is the actual output from `go test -race` on lesson 06 before
// the fix. See LESSONS.md, "The race detector found a race in the lesson about
// races".
const sampleReport = `WARNING: DATA RACE
Read at 0x00c0002a211c by goroutine 2321:
  ??()
      -:0 +0x104ceae0c
  sync/atomic.AddInt32()
      <autogenerated>:1 +0x14

Previous write at 0x00c0002a211c by goroutine 2224:
  main.mainDoesNotWait()
      starting.go:71 +0xc4
  main.TestMainDoesNotWait()
      starting_test.go:35 +0x28

Goroutine 2321 (running) created at:
  main.mainDoesNotWait()
      starting.go:65 +0x40
  main.TestMainDoesNotWait()
      starting_test.go:35 +0x28`

// ReportSection is one part of a report, with what it tells you.
type ReportSection struct {
	Name     string
	Tells    string
	Priority int // 1 is where to look first
}

// anatomy breaks a report into its four parts. The fourth is the one people
// skip and the one that usually identifies the bug.
func anatomy() []ReportSection {
	return []ReportSection{
		{
			Name:     "the address (0x00c0002a211c)",
			Tells:    "the same address in both halves means the same variable; different addresses mean two races",
			Priority: 3,
		},
		{
			Name:     "the current access, with its stack",
			Tells:    "where one half happened; often inside a library rather than your code",
			Priority: 2,
		},
		{
			Name:     "the previous access, with its stack",
			Tells:    "the other half; at least one of the two is a write",
			Priority: 2,
		},
		{
			Name:     "where each goroutine was CREATED",
			Tells:    "usually the actual bug: the go statement is yours even when the access sites are not",
			Priority: 1,
		},
		{
			Name:     "...unless a helper started it",
			Tells:    "sync.WaitGroup.Go and errgroup.Go appear as the creation site instead of your line; look one frame further",
			Priority: 1,
		},
	}
}

// whatThisReportSaid walks the sample, because reading one well is the skill.
func whatThisReportSaid() []string {
	return []string{
		"both halves are at 0x00c0002a211c, so it is one variable",
		"one half is sync/atomic.AddInt32: a goroutine incrementing the counter",
		"the other is starting.go:71, which was `return atomic.LoadInt32(&finished)`",
		"line 71 was a RETURN statement, which is not obviously an access at all",
		"the function had a NAMED return: `return x` compiles to `finished = x; return`",
		"that assignment is a plain, non-atomic write to the variable being incremented",
		"the fix: drop the named return, and use atomic.Int32 so a plain access is unwritable",
	}
}

// waitGroupGoObscuresTheCreationSite is worth knowing before you rely on the
// creation stack.
//
// Since Go 1.25, sync.WaitGroup.Go starts the goroutine, so a report says:
//
//	Goroutine 8 (running) created at:
//	  sync.(*WaitGroup).Go()
//	      .../sync/waitgroup.go:238
//	  testing.tRunner()
//
// and your own line is not in it at all. The same happens with errgroup.Go and
// any other helper that takes a func and starts it.
//
// The frame above the helper is the one you want. When even that is unhelpful,
// the ACCESS stacks still name your code, and they are what is left.
func waitGroupGoObscuresTheCreationSite() []string {
	return []string{
		"sync.WaitGroup.Go (1.25) and errgroup.Go start the goroutine themselves",
		"so \"created at\" names the helper, not your line",
		"look one frame further up, past the helper, for your call site",
		"a bare `go func(){...}()` still points straight at your code",
	}
}

// actOnIt is the checklist, in order.
func actOnIt() []string {
	return []string{
		"1. read the CREATED AT stacks first: usually your go statement, unless a helper started it",
		"2. identify the variable from the address, not from the function names",
		"3. decide which access should not be happening, rather than adding a lock and rerunning",
		"4. prefer not sharing at all, then immutability, then an atomic, then a mutex",
		"5. rerun with -count=10: one green run proves very little about a race",
		"6. if the fix was \"add a mutex\" and you cannot say which edge it creates, it is not a fix",
	}
}

// commandsForRaces is the working set.
func commandsForRaces() map[string]string {
	return map[string]string{
		"go test -race ./...":            "the whole suite, which is the only useful scope",
		"go test -race -count=10 ./...":  "ten runs, to vary the interleaving",
		"go test -race -run TestX ./pkg": "one test, when iterating on a fix",
		"go build -race && ./app":        "a binary with the detector, for a canary instance",
		"GORACE=halt_on_error=1":         "stop at the first report rather than collecting them",
		"GORACE=history_size=7":          "a longer access history: slower, finds more",
		"GORACE=log_path=/tmp/race":      "write reports to files rather than stderr",
	}
}

// demoReading prints the anatomy against the real report.
func demoReading() {
	fmt.Println("  a real report, from this repository's lesson 06:")
	for _, line := range strings.Split(sampleReport, "\n") {
		fmt.Printf("    | %s\n", line)
	}

	fmt.Println("\n  its four parts, in the order to read them:")
	sections := anatomy()
	for priority := 1; priority <= 3; priority++ {
		for _, s := range sections {
			if s.Priority != priority {
				continue
			}
			fmt.Printf("    [%d] %-38s %s\n", priority, s.Name, s.Tells)
		}
	}

	fmt.Println("\n  what this particular report said:")
	for _, s := range whatThisReportSaid() {
		fmt.Printf("    %s\n", s)
	}

	fmt.Println("\n  a caveat on the creation stack:")
	for _, s := range waitGroupGoObscuresTheCreationSite() {
		fmt.Printf("    %s\n", s)
	}

	fmt.Println("\n  acting on one:")
	for _, s := range actOnIt() {
		fmt.Printf("    %s\n", s)
	}

	fmt.Println("\n  the commands:")
	for _, k := range []string{
		"go test -race ./...",
		"go test -race -count=10 ./...",
		"go test -race -run TestX ./pkg",
		"go build -race && ./app",
		"GORACE=halt_on_error=1",
		"GORACE=history_size=7",
		"GORACE=log_path=/tmp/race",
	} {
		fmt.Printf("    %-32s %s\n", k, commandsForRaces()[k])
	}
}
