// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

// A page of books, Relay style.
type BookConnection struct {
	Edges    []BookEdge `json:"edges"`
	PageInfo *PageInfo  `json:"pageInfo"`
	// The total, which is optional in the Relay spec and expensive in practice. See the pagination package: an exact
	// count is a full scan every time, so a real API either omits it or returns an estimate.
	TotalCount int `json:"totalCount"`
}

type BookEdge struct {
	Cursor string `json:"cursor"`
	Node   *Book  `json:"node"`
}

// The input for creating a book.
//
// A separate INPUT type rather than reusing Book, because the two are genuinely different: Book has an id and an
// author object, and the input has neither. GraphQL enforces the distinction (an input type cannot be used as an
// output type or the reverse), which is one of the places the type system stops a mistake REST does not.
type CreateBookInput struct {
	Title      string `json:"title"`
	AuthorID   string `json:"authorId"`
	PriceCents int    `json:"priceCents"`
	// The idempotency key, carried in the INPUT rather than in a header.
	//
	// GraphQL has one endpoint and one HTTP request can carry several mutations, so a header applies to all of them
	// or none. Per-mutation idempotency has to be in the arguments, and that is a difference from REST worth
	// stating.
	IdempotencyKey *string `json:"idempotencyKey,omitempty"`
}

// A mutation result that carries its own errors.
//
// # Why not just return Book and use the errors array
//
// Because GraphQL's top-level `errors` array is untyped: a message, a path and an optional extensions map. A
// client cannot switch on it without parsing strings, and a schema change to the error shape is invisible.
//
// A result union or a result type with a typed errors field puts the expected failures in the SCHEMA, where they
// are typed, documented and versioned. The top-level array is then reserved for the unexpected: a bug, a timeout,
// a permission failure.
//
// This is the single most consequential GraphQL design decision and it has no REST equivalent, because REST has
// status codes.
type CreateBookResult struct {
	Book   *Book       `json:"book,omitempty"`
	Errors []UserError `json:"errors"`
}

type Mutation struct {
}

// Relay's page metadata. The four fields are named by the spec and two of them are commonly wrong.
type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type Query struct {
}

type UserError struct {
	Field   *string   `json:"field,omitempty"`
	Message string    `json:"message"`
	Code    ErrorCode `json:"code"`
}

type ErrorCode string

const (
	ErrorCodeValidation       ErrorCode = "VALIDATION"
	ErrorCodeNotFound         ErrorCode = "NOT_FOUND"
	ErrorCodeConflict         ErrorCode = "CONFLICT"
	ErrorCodePermissionDenied ErrorCode = "PERMISSION_DENIED"
)

var AllErrorCode = []ErrorCode{
	ErrorCodeValidation,
	ErrorCodeNotFound,
	ErrorCodeConflict,
	ErrorCodePermissionDenied,
}

func (e ErrorCode) IsValid() bool {
	switch e {
	case ErrorCodeValidation, ErrorCodeNotFound, ErrorCodeConflict, ErrorCodePermissionDenied:
		return true
	}
	return false
}

func (e ErrorCode) String() string {
	return string(e)
}

func (e *ErrorCode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ErrorCode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ErrorCode", str)
	}
	return nil
}

func (e ErrorCode) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ErrorCode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ErrorCode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
